openapi: 3.0.2
servers:
  - url: /v3
info:
  description: |-
    大事件 API 接口文档
  version: 1.0.19-SNAPSHOT
  title: Big Event - OpenAPI 3.0
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: yu_mingm623@163.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

tags:
  - name: user
    description: 用户类接口
  - name: category
    description: 文章分类接口
  - name: article
    description: 文章接口

paths:
  /user/register:
    post:
      tags:
        - user
      summary: 用户注册
      description: 新用户注册接口
      operationId: register
      responses:
        '200':
          description: 操作成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserRegisterResponse'

        '405':
          description: 不合法的输入

      requestBody:
        description: Request请求数据示例
        required: True
        content:
          x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/UserRegister"


  /user/login:
    post:
      tags:
        - user
      summary: 用户登录
      description: 用户登录接口
      operationId: login
      responses:
        '200':
          description: 操作成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserRegisterResponse'

        '405':
          description: 不合法的输入

      requestBody:
        description: Request请求数据示例
        required: True
        content:
          x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/UserRegister"

components:
  schemas:
    UserRegisterResponse:
      required:
        - code
      properties:
        code:
          type: number
          example: 0
          description: 响应码, 0 表示成功，1 表示失败
        message:
          type: string
          example: "操作成功"
          description: "返回消息"
        data:
          type: object
          example: null
          description: "返回数据"

    UserLoginResponse:
      required:
        - code
      properties:
        code:
          type: number
          example: 0
          description: 响应码, 0 表示成功，1 表示失败
        message:
          type: string
          example: "操作成功"
          description: "返回消息"
        data:
          type: string
          example: "eyJ.....M"
          description: "返回 jwt 数据"

    UserRegister:
      required:
        - username
        - password

      properties:
        username:
          type: string
          example: 张三
          description: 用户名，5-16位非空字符

        password:
          type: string
          example: asd123s12xo79
          description: 密码，5-16位非空字符

    User:
      x-swagger-router-model: io.swagger.petstore.model.User
      properties:
        id:
          type: integer
          format: int64
          example: 10001

        username:
          type: string
          example: 张三

        password:
          type: string
          example: asd123s12xo79

        nickname:
          type: string
          example: 三儿

        email:
          type: string
          example: zhangsan@example.com

        userPic:
          type: string
          example: /static/avatar/zhangsan.png

        createTime:
          type: string
          example: 2024-01-01 00:00:01

        updateTime:
          type: string
          example: 2024-01-02 00:00:01

      xml:
        name: user
      type: object
